version: '3.4'

services:

  myrabbitmq:
    image: rabbitmq:3-management
    container_name: myrabbitmq
    restart: "on-failure"
    ports:
        - "5672:5672"
        - "15672:15672"
    
  mymongodb:
    image: mongo:latest
    container_name: mymongodb
    restart: "on-failure"
    environment:
        - MONGO_INITDB_DATABASE=DefaultMongoDb
    ports:
        - "27017-27019:27017-27019"
    
  identityservice:
    image: mustafasalih/sample-dotnet-microservices:identityservice
    container_name: identityservice
    restart: "on-failure"
    build:
     context: ../../
     dockerfile: Microservices/OnlineMovieStore/src/IdentityService/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
    
  movieservice:
    image: mustafasalih/sample-dotnet-microservices:movieservice
    container_name: movieservice
    restart: "on-failure"
    build:
     context: ../../
     dockerfile: Microservices/OnlineMovieStore/src/MovieService/Movie.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
    
  cartservice:
    image: mustafasalih/sample-dotnet-microservices:cartservice
    container_name: cartservice
    restart: "on-failure"
    build:
     context: ../../
     dockerfile: Microservices/OnlineMovieStore/src/CartService/Cart.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "identityservice"
    
  paymentservice:
    image: mustafasalih/sample-dotnet-microservices:paymentservice
    container_name: paymentservice
    restart: "on-failure"
    build:
     context: ../../
     dockerfile: Microservices/OnlineMovieStore/src/PaymentService/Payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "identityservice"
      - "cartservice"
    
  getewayservice:
    image: mustafasalih/sample-dotnet-microservices:getewayservice
    container_name: getewayservice
    restart: "on-failure"
    build:
     context: ../../
     dockerfile: Microservices/OnlineMovieStore/src/GatewayService/Gateway.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "identityservice"
      - "movieservice"
      - "cartservice"
    
  websiteapp:
    image: mustafasalih/sample-dotnet-microservices:websiteapp
    container_name: websiteapp
    restart: "on-failure"
    build:
     context: ../../
     dockerfile: Microservices/OnlineMovieStore/src/Web.MovieStore/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "getewayservice"
