version: '3.4'

services:
  myaspnetcoreapi:
    image: mustafasalih/aspnetcore31:api1
    build:
     context: .
     dockerfile: netCoreAPITest/Dockerfile
    ports: 
      - "5501:443"
      - "5500:80"
