version: '3.4'

services:
  identityservice:
    image: mustafasalih/sample-dotnet-microservices:identityservice
    build:
     context: .
     dockerfile: src/IdentityService/Samp.Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1020:80"

  movieservice:
    image: mustafasalih/sample-dotnet-microservices:movieservice
    build:
     context: .
     dockerfile: src/MovieService/Samp.Movie.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1030:80"

  cartservice:
    image: mustafasalih/sample-dotnet-microservices:cartservice
    build:
     context: .
     dockerfile: src/CartService/Samp.Cart.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1050:80"
    depends_on:
      - "identityservice"
          
  getewayservice:
    image: mustafasalih/sample-dotnet-microservices:getewayservice
    build:
     context: .
     dockerfile: src/GatewayService/Samp.Gateway.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1010:80"
    depends_on:
      - "identityservice"
      - "movieservice"
      - "cartservice"