version: '3.4'

services:
  myrabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: myrabbitmq
    networks:
    - mynetwork
    restart: "on-failure"
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./volumes/rabbitmq/log/:/var/log/rabbitmq

  mymongodb:
    image: mongo:latest
    container_name: mymongodb
    networks:
    - mynetwork
    restart: "on-failure"
    environment:
        - MONGO_INITDB_DATABASE=MongoDb
    volumes:
        - ./volumes/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - ./volumes/mongo:/data/db
    ports:
        - "27017-27019:27017-27019"

  identityservice:
    image: mustafasalih/sample-dotnet-microservices:identityservice
    container_name: identityservice
    networks:
    - mynetwork
    restart: "on-failure"
    build:
     context: .
     dockerfile: src/IdentityService/Samp.Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1020
    ports: 
      - "1020:1020"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"

  movieservice:
    image: mustafasalih/sample-dotnet-microservices:movieservice
    container_name: movieservice
    networks:
    - mynetwork
    restart: "on-failure"
    build:
     context: .
     dockerfile: src/MovieService/Samp.Movie.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1030
    ports: 
      - "1030:1030"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"

  cartservice:
    image: mustafasalih/sample-dotnet-microservices:cartservice
    container_name: cartservice
    networks:
    - mynetwork
    restart: "on-failure"
    build:
     context: .
     dockerfile: src/CartService/Samp.Cart.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1050
    ports: 
      - "1050:1050"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "identityservice"

  paymentservice:
    image: mustafasalih/sample-dotnet-microservices:paymentservice
    container_name: paymentservice
    networks:
    - mynetwork
    restart: "on-failure"
    build:
     context: .
     dockerfile: src/PaymentService/Samp.Payment.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1040
    ports: 
      - "1040:1040"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "identityservice"
      - "cartservice"
          
  getewayservice:
    image: mustafasalih/sample-dotnet-microservices:getewayservice
    container_name: getewayservice
    networks:
    - mynetwork
    restart: "on-failure"
    build:
     context: .
     dockerfile: src/GatewayService/Samp.Gateway.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1010
      - USEDOCKEROCELOT=true
    ports: 
      - "1010:1010"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "identityservice"
      - "movieservice"
      - "cartservice"

  websiteapp:
    image: mustafasalih/sample-dotnet-microservices:websiteapp
    container_name: websiteapp
    networks:
    - mynetwork
    restart: "on-failure"
    build:
     context: .
     dockerfile: src/Samp.Web.MovieStore/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:2000
    ports: 
      - "2000:2000"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"
      - "getewayservice"

networks:
  mynetwork:
     driver: bridge