version: '3.4'

services:
  identityservice:
    image: mustafasalih/sample-dotnet-microservices:identityservice
    build:
     context: .
     dockerfile: src/IdentityService/Samp.Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1020:80"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"

  movieservice:
    image: mustafasalih/sample-dotnet-microservices:movieservice
    build:
     context: .
     dockerfile: src/MovieService/Samp.Movie.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1030:80"
    depends_on:
      - "myrabbitmq"
      - "mymongodb"

  cartservice:
    image: mustafasalih/sample-dotnet-microservices:cartservice
    build:
     context: .
     dockerfile: src/CartService/Samp.Cart.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1050:80"
    depends_on:
      - "identityservice"
      - "myrabbitmq"
      - "mymongodb"
          
  getewayservice:
    image: mustafasalih/sample-dotnet-microservices:getewayservice
    build:
     context: .
     dockerfile: src/GatewayService/Samp.Gateway.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "1010:80"
    depends_on:
      - "identityservice"
      - "movieservice"
      - "cartservice"
      - "myrabbitmq"
      - "mymongodb"

  myrabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./volumes/rabbitmq/log/:/var/log/rabbitmq

  mymongodb:
    image: mongo:latest
    environment:
        - MONGO_INITDB_DATABASE=MongoDb
    volumes:
        - ./volumes/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - ./volumes/mongo:/data/db
    ports:
        - "27017-27019:27017-27019"